source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NNButton_Example', :exclusive => true do
  pod "NNButton", :path => "../"
end

target 'NNButton_Tests', :exclusive => true do
  pod "NNButton", :path => "../"

  
end
