source 'https://github.com/noughts/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'NNButton_Example', :exclusive => true do
  pod "NNButton", :path => "../"
end

target 'NNButton_Tests', :exclusive => true do
  pod "NNButton", :path => "../"

  
end
